/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaPop: typeof import('./src/components/areaPop.vue')['default']
    Charts: typeof import('./src/components/charts/charts.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    GhostButton: typeof import('./src/components/GhostButton.vue')['default']
    InputCom: typeof import('./src/components/inputCom.vue')['default']
    KlineSvg: typeof import('./src/components/klineSvg.vue')['default']
    LoadMore: typeof import('./src/components/LoadMore.vue')['default']
    NationalityList: typeof import('./src/components/nationality-list/nationalityList.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlidePop: typeof import('./src/components/slidePop.vue')['default']
    Tab: typeof import('./src/components/tab.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    UserInfo: typeof import('./src/components/user-info.vue')['default']
    WwTab: typeof import('./src/components/ww-tab.vue')['default']
  }
}