/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCenter: typeof import('./../components/activityCenter.vue')['default']
    BottomButton: typeof import('./../components/bottom-button.vue')['default']
    CloseButton: typeof import('./../components/CloseButton.vue')['default']
    CodeInput: typeof import('./../components/CodeInput.vue')['default']
    Empty: typeof import('./../components/empty.vue')['default']
    FaqItem: typeof import('./../components/faqItem.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    Grid: typeof import('./../components/grid.vue')['default']
    InputCom: typeof import('./../components/inputCom.vue')['default']
    Item: typeof import('./../components/item.vue')['default']
    Keypad: typeof import('./../components/Keypad.vue')['default']
    LangSelectDropdown: typeof import('./../components/LangSelectDropdown.vue')['default']
    LoadMore: typeof import('./../components/LoadMore.vue')['default']
    NationalityList: typeof import('./../components/nationality-list/nationalityList.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    PayKeypad: typeof import('./../components/payKeypad.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockItem: typeof import('./../components/stock-item.vue')['default']
    Tab: typeof import('./../components/tab.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
