/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaPop: typeof import('./../components/areaPop.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    Charts: typeof import('./../components/Eharts/charts.vue')['default']
    copy: typeof import('./../components/slidePop copy.vue')['default']
    Echarts: typeof import('./../components/echarts.vue')['default']
    Empty: typeof import('./../components/empty.vue')['default']
    FxCountryList: typeof import('./../components/fx-country-list/index.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    InputCom: typeof import('./../components/inputCom.vue')['default']
    Kline: typeof import('./../components/Kline.vue')['default']
    KlineChat: typeof import('./../components/klineChat.vue')['default']
    KlineSvg: typeof import('./../components/klineSvg.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlidePop: typeof import('./../components/slidePop.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    UserInfo: typeof import('./../components/user-info.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanLink: typeof import('vant/es')['Link']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanStep: typeof import('vant/es')['Step']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSteps: typeof import('vant/es')['Steps']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
    WwTab: typeof import('./../components/ww-tab.vue')['default']
  }
}
