/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/advancedCtf/': RouteRecordInfo<'/advancedCtf/', '/advancedCtf', Record<never, never>, Record<never, never>>,
    '/authentication/': RouteRecordInfo<'/authentication/', '/authentication', Record<never, never>, Record<never, never>>,
    'certificationCenter': RouteRecordInfo<'certificationCenter', '/certificationCenter', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'deal': RouteRecordInfo<'deal', '/deal', Record<never, never>, Record<never, never>>,
    '/deal/components/indicator': RouteRecordInfo<'/deal/components/indicator', '/deal/components/indicator', Record<never, never>, Record<never, never>>,
    '/deal/components/quickly': RouteRecordInfo<'/deal/components/quickly', '/deal/components/quickly', Record<never, never>, Record<never, never>>,
    '/deal/exchange/channel-in': RouteRecordInfo<'/deal/exchange/channel-in', '/deal/exchange/channel-in', Record<never, never>, Record<never, never>>,
    '/deal/exchange/channel-out': RouteRecordInfo<'/deal/exchange/channel-out', '/deal/exchange/channel-out', Record<never, never>, Record<never, never>>,
    '/deal/exchange/charge-bank': RouteRecordInfo<'/deal/exchange/charge-bank', '/deal/exchange/charge-bank', Record<never, never>, Record<never, never>>,
    '/deal/exchange/rechargeList': RouteRecordInfo<'/deal/exchange/rechargeList', '/deal/exchange/rechargeList', Record<never, never>, Record<never, never>>,
    '/deal/exchange/report': RouteRecordInfo<'/deal/exchange/report', '/deal/exchange/report', Record<never, never>, Record<never, never>>,
    '/deal/exchange/withdraw-bank': RouteRecordInfo<'/deal/exchange/withdraw-bank', '/deal/exchange/withdraw-bank', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'news': RouteRecordInfo<'news', '/news', Record<never, never>, Record<never, never>>,
    'optional': RouteRecordInfo<'optional', '/optional', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/bindVerify/bindVerify': RouteRecordInfo<'/profile/bindVerify/bindVerify', '/profile/bindVerify/bindVerify', Record<never, never>, Record<never, never>>,
    '/profile/changeFundsPassword/changeFundsPassword': RouteRecordInfo<'/profile/changeFundsPassword/changeFundsPassword', '/profile/changeFundsPassword/changeFundsPassword', Record<never, never>, Record<never, never>>,
    '/profile/changePassword/changePassword': RouteRecordInfo<'/profile/changePassword/changePassword', '/profile/changePassword/changePassword', Record<never, never>, Record<never, never>>,
    '/profile/exchangeRate/exchangeRate': RouteRecordInfo<'/profile/exchangeRate/exchangeRate', '/profile/exchangeRate/exchangeRate', Record<never, never>, Record<never, never>>,
    '/profile/payMentMethod/add': RouteRecordInfo<'/profile/payMentMethod/add', '/profile/payMentMethod/add', Record<never, never>, Record<never, never>>,
    '/profile/payMentMethod/list': RouteRecordInfo<'/profile/payMentMethod/list', '/profile/payMentMethod/list', Record<never, never>, Record<never, never>>,
    '/profile/payMentMethod/selectPay': RouteRecordInfo<'/profile/payMentMethod/selectPay', '/profile/payMentMethod/selectPay', Record<never, never>, Record<never, never>>,
    '/profile/safetyPage/safety': RouteRecordInfo<'/profile/safetyPage/safety', '/profile/safetyPage/safety', Record<never, never>, Record<never, never>>,
    'quotes': RouteRecordInfo<'quotes', '/quotes', Record<never, never>, Record<never, never>>,
    '/quotes/[accountChange]': RouteRecordInfo<'/quotes/[accountChange]', '/quotes/:accountChange', { accountChange: ParamValue<true> }, { accountChange: ParamValue<false> }>,
    'openTrade': RouteRecordInfo<'openTrade', '/quotes/:openTrade', { openTrade: ParamValue<true> }, { openTrade: ParamValue<false> }>,
    'commodities': RouteRecordInfo<'commodities', '/quotes/commodities/:commodities?', { commodities: ParamValue<true> }, { commodities: ParamValue<false> }>,
    'commoditiesOrderList': RouteRecordInfo<'commoditiesOrderList', '/quotes/commoditiesOrderList/:commoditiesOrderList?', { commoditiesOrderList: ParamValue<true> }, { commoditiesOrderList: ParamValue<false> }>,
    'usStockIndexDetail': RouteRecordInfo<'usStockIndexDetail', '/quotes/usStockIndexDetail/:usStockIndexDetail?', { usStockIndexDetail: ParamValue<true> }, { usStockIndexDetail: ParamValue<false> }>,
    'UsStockMore': RouteRecordInfo<'UsStockMore', '/quotes/UsStockMore/:UsStockMore?', { UsStockMore: ParamValue<true> }, { UsStockMore: ParamValue<false> }>,
    'accountChange': RouteRecordInfo<'accountChange', '/quotes/accountChange/:accountChange', Record<never, never>, Record<never, never>>,
    '/quotes/component/accountChangeCom/tab-item': RouteRecordInfo<'/quotes/component/accountChangeCom/tab-item', '/quotes/component/accountChangeCom/tab-item', Record<never, never>, Record<never, never>>,
    '/quotes/component/banner': RouteRecordInfo<'/quotes/component/banner', '/quotes/component/banner', Record<never, never>, Record<never, never>>,
    '/quotes/component/chat-item': RouteRecordInfo<'/quotes/component/chat-item', '/quotes/component/chat-item', Record<never, never>, Record<never, never>>,
    '/quotes/component/commoditiesOrderItem/order-item': RouteRecordInfo<'/quotes/component/commoditiesOrderItem/order-item', '/quotes/component/commoditiesOrderItem/order-item', Record<never, never>, Record<never, never>>,
    '/quotes/component/grid': RouteRecordInfo<'/quotes/component/grid', '/quotes/component/grid', Record<never, never>, Record<never, never>>,
    '/quotes/component/indicator': RouteRecordInfo<'/quotes/component/indicator', '/quotes/component/indicator', Record<never, never>, Record<never, never>>,
    '/quotes/component/notice': RouteRecordInfo<'/quotes/component/notice', '/quotes/component/notice', Record<never, never>, Record<never, never>>,
    '/quotes/component/openTradeCom/search-page': RouteRecordInfo<'/quotes/component/openTradeCom/search-page', '/quotes/component/openTradeCom/search-page', Record<never, never>, Record<never, never>>,
    '/quotes/component/openTradeCom/tab-page': RouteRecordInfo<'/quotes/component/openTradeCom/tab-page', '/quotes/component/openTradeCom/tab-page', Record<never, never>, Record<never, never>>,
    '/quotes/component/openTradeCom/tab-table-page': RouteRecordInfo<'/quotes/component/openTradeCom/tab-table-page', '/quotes/component/openTradeCom/tab-table-page', Record<never, never>, Record<never, never>>,
    '/quotes/component/rank': RouteRecordInfo<'/quotes/component/rank', '/quotes/component/rank', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
    'ScrollCache': RouteRecordInfo<'ScrollCache', '/scroll-cache', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
