/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'aboutUs': RouteRecordInfo<'aboutUs', '/aboutUs', Record<never, never>, Record<never, never>>,
    'activityDetail': RouteRecordInfo<'activityDetail', '/activityDetail', Record<never, never>, Record<never, never>>,
    '/buy/': RouteRecordInfo<'/buy/', '/buy', Record<never, never>, Record<never, never>>,
    'buySuccess': RouteRecordInfo<'buySuccess', '/buy/success', Record<never, never>, Record<never, never>>,
    'exchange': RouteRecordInfo<'exchange', '/exchange', Record<never, never>, Record<never, never>>,
    'faqList': RouteRecordInfo<'faqList', '/faqList', Record<never, never>, Record<never, never>>,
    'forgotPassword': RouteRecordInfo<'forgotPassword', '/forgot-password', Record<never, never>, Record<never, never>>,
    'inviteFriends': RouteRecordInfo<'inviteFriends', '/inviteFriends', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'Market': RouteRecordInfo<'Market', '/market', Record<never, never>, Record<never, never>>,
    'productDetailss': RouteRecordInfo<'productDetailss', '/market/productDetail', Record<never, never>, Record<never, never>>,
    'monthlySalary': RouteRecordInfo<'monthlySalary', '/monthlySalary', Record<never, never>, Record<never, never>>,
    'news': RouteRecordInfo<'news', '/news', Record<never, never>, Record<never, never>>,
    'addCommunity': RouteRecordInfo<'addCommunity', '/news/addCommunity', Record<never, never>, Record<never, never>>,
    '/news/com/item': RouteRecordInfo<'/news/com/item', '/news/com/item', Record<never, never>, Record<never, never>>,
    '/news/newDetail/': RouteRecordInfo<'/news/newDetail/', '/news/newDetail', Record<never, never>, Record<never, never>>,
    'NoticeDetail': RouteRecordInfo<'NoticeDetail', '/noticeDetail', Record<never, never>, Record<never, never>>,
    'Notify': RouteRecordInfo<'Notify', '/notify', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'BankAccount': RouteRecordInfo<'BankAccount', '/profile/bankAccount', Record<never, never>, Record<never, never>>,
    'addBank': RouteRecordInfo<'addBank', '/profile/bankAccount/addBank', Record<never, never>, Record<never, never>>,
    '/profile/changePassword/changePassword': RouteRecordInfo<'/profile/changePassword/changePassword', '/profile/changePassword/changePassword', Record<never, never>, Record<never, never>>,
    'languange': RouteRecordInfo<'languange', '/profile/languange', Record<never, never>, Record<never, never>>,
    'Receive': RouteRecordInfo<'Receive', '/receive', Record<never, never>, Record<never, never>>,
    'reward': RouteRecordInfo<'reward', '/reward', Record<never, never>, Record<never, never>>,
    'richTextDetail': RouteRecordInfo<'richTextDetail', '/richTextDetail', Record<never, never>, Record<never, never>>,
    'signIn': RouteRecordInfo<'signIn', '/signIn', Record<never, never>, Record<never, never>>,
    'taskBonus': RouteRecordInfo<'taskBonus', '/taskBonus', Record<never, never>, Record<never, never>>,
    'team': RouteRecordInfo<'team', '/team', Record<never, never>, Record<never, never>>,
    'wallet': RouteRecordInfo<'wallet', '/wallet', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/cashierCenter': RouteRecordInfo<'/wallet/exchange/cashierCenter', '/wallet/exchange/cashierCenter', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/cashierCenter-withdraw': RouteRecordInfo<'/wallet/exchange/cashierCenter-withdraw', '/wallet/exchange/cashierCenter-withdraw', Record<never, never>, Record<never, never>>,
    'Deposit': RouteRecordInfo<'Deposit', '/wallet/exchange/channel-out', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/charge-bank': RouteRecordInfo<'/wallet/exchange/charge-bank', '/wallet/exchange/charge-bank', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/deposit-preview': RouteRecordInfo<'/wallet/exchange/deposit-preview', '/wallet/exchange/deposit-preview', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/deposit-success': RouteRecordInfo<'/wallet/exchange/deposit-success', '/wallet/exchange/deposit-success', Record<never, never>, Record<never, never>>,
    'Withdrawbank': RouteRecordInfo<'Withdrawbank', '/wallet/exchange/withdraw-bank', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/withdraw-preview': RouteRecordInfo<'/wallet/exchange/withdraw-preview', '/wallet/exchange/withdraw-preview', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/withdraw-success': RouteRecordInfo<'/wallet/exchange/withdraw-success', '/wallet/exchange/withdraw-success', Record<never, never>, Record<never, never>>,
    '/wallet/exchange/withdraw-usdt': RouteRecordInfo<'/wallet/exchange/withdraw-usdt', '/wallet/exchange/withdraw-usdt', Record<never, never>, Record<never, never>>,
    'walletLogs': RouteRecordInfo<'walletLogs', '/wallet/walletLogs', Record<never, never>, Record<never, never>>,
    'webview': RouteRecordInfo<'webview', '/webview', Record<never, never>, Record<never, never>>,
    '/webview/webview': RouteRecordInfo<'/webview/webview', '/webview/webview', Record<never, never>, Record<never, never>>,
    'weeklySalary': RouteRecordInfo<'weeklySalary', '/weeklySalary', Record<never, never>, Record<never, never>>,
    'yearSalary': RouteRecordInfo<'yearSalary', '/yearSalary', Record<never, never>, Record<never, never>>,
  }
}
